# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    param_fetcher_listener: true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    view:
        view_response_listener: true
        formats:
            json: true
        mime_types:
            json: ['application/json', 'application/jsonld', 'application/json;version=1.0', 'application/json;version=1.1']
    serializer:
        serialize_null: true
