# Project language
language: php

# Start mysql service
services:
    - docker

# Settings version PHP
php:
    - 7.2

# Adding custom domains
addons:
    hosts:
        - db.dockit.site

# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache/files

# Update composer
before-install:
    - composer self-update
    - docker-compose -f .docker/docker-compose.yml build
    - docker-compose -f .docker/docker-compose.yml up -d

# Install composer dependencies,
# Create database, schema and fixtures
install:
    - composer install

# Run script
script:
    - php bin/console doctrine:migrations:migrate -n --env=test
    - php bin/console doctrine:schema:validate

# Run after script, regardless of the outcome of the tests
after_script:
    - docker-compose stop
    - docker-compose rm -f
