# Project language
language: php

# Start mysql service
services:
    - docker

# Settings version PHP
php:
    - 7.2

# Update composer
before-install:
    - docker-compose -f .docker/docker-compose.yml

# Install composer dependencies,
# Create database, schema and fixtures
install:
    - composer install
    - php bin/console doctrine:migrations:migrate -n --env=test

# Run script
script:
    - php bin/console doctrine:schema:validate
