version: '3.7'
services:

    symfony_php:
        build: ./code
        ports:
            - "9000:9001"
        volumes:
            - ./../:/var/www/symfony:cached
        links:
            - symfony_db:db.dockit.site
        extra_hosts:
            - "docker-host.localhost:127.0.0.1"

    symfony_4_web:
        build: ./server
        ports:
            - "80:80"
        links:
            - symfony_php
        volumes:
            - ./../:/var/www/symfony:cached

    symfony_db:
        image: mariadb/server:10.3
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - ./mysql:/var/lib/mysql
